### ISSUE TITLE
Add `call_module_function_promise` to deal with async functions

### ISSUE THREAD

**Issue by j-mueller** [lublak/typst-ctxjs-package#1]
I'd like to call an `async` function in JavaScript. When I do this with `call_module_function` I get an error

> error: plugin errored with: failed to call function: Error converting from js 'promise' into type 'JSBytesValue'

I believe this can be fixed by adding a `fn call_module_function_promise` to `lib.rs` that calls `finish` on the `Promise`. Happy to try implementing this myself if this is the right thing to do.

**Comment by lublak** [comment]
@j-mueller 

I have not yet considered synchronisation in the project. But I think that's a good feature request.
I think it makes the most sense to check in the existing function whether there is a promise back instead of establishing a new function. 
So an option that a promise is ‘converted’ to a JSBytesValue.  The implemantion position would be here: https://github.com/lublak/typst-ctxjs-package/blob/main/src/value.rs
This would benefit all functions that return a promise value.
I will be on holiday from Wednesday until Tuesday. I can't guarantee whether I'll be able to do it before then. But I can take it over and try to make it possible before my holiday.

**Comment by lublak** [comment]
@j-mueller I think it's a quick function. I will do it today, can you test it then?

**Comment by lublak** [comment]
fix in: https://github.com/lublak/typst-ctxjs-package/commit/05cf075711d1b112bae88e02c7470f7ad5633194

**Comment by j-mueller** [comment]
@lublak  Yep it works, thank you!

**Comment by lublak** [comment]
@j-mueller awesome :) i published a new version to the universe. https://github.com/typst/packages/pull/1016
It will take a few days and then it should also be available in the Universe.

**Comment by j-mueller** [comment]
Amazing, thank you!

**Comment by lublak** [comment]
@j-mueller it's now on universe

**Comment by j-mueller** [comment]
Thanks, I already made a package based on it (and inspired by your echarms package): https://typst.app/universe/package/nulite/

**Comment by lublak** [comment]
@j-mueller awesome! :) 
The first one implemented was echarming without any further usability of the Javascript runtime. But I thought, hey, others might find it useful too. That's how ctxjs came about. Echarming should then serve as an example. As a small recommendation for the next release. The best context name here would be the package name "@preview/nulite".
